### ISSUE TITLE
Orebfuscator issue on 1.13.x

### ISSUE THREAD

**Issue by DmitryRendov** [DmitryRendov/mob-server#92]
[07:08:34] [Server thread/WARN]: java.lang.NullPointerException
[07:08:34] [Server thread/WARN]:        at com.lishid.orebfuscator.hook.ProtocolLibHook$1.onPacketSending(ProtocolLibHook.java:86)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:367)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:66)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:332)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:302)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127)
[07:08:34] [Server thread/WARN]:        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.b(NetworkManager.java:194)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.NetworkManager.sendPacket(NetworkManager.java:158)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1396)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1369)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerChunk.sendChunk(PlayerChunk.java:121)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerChunk.a(PlayerChunk.java:63)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerChunkMap.addPlayer(PlayerChunkMap.java:261)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:693)
[07:08:34] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.teleport(CraftPlayer.java:626)
[07:08:34] [Server thread/WARN]:        at com.earth2me.essentials.Teleport.now(Teleport.java:139)
[07:08:34] [Server thread/WARN]:        at com.earth2me.essentials.Teleport.teleport(Teleport.java:198)
[07:08:34] [Server thread/WARN]:        at com.earth2me.essentials.Teleport.warp(Teleport.java:255)
[07:08:34] [Server thread/WARN]:        at com.earth2me.essentials.commands.Commandwarp.warpUser(Commandwarp.java:112)
[07:08:34] [Server thread/WARN]:        at com.earth2me.essentials.commands.Commandwarp.run(Commandwarp.java:47)
[07:08:34] [Server thread/WARN]:        at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157)
[07:08:34] [Server thread/WARN]:        at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:522)
[07:08:34] [Server thread/WARN]:        at com.earth2me.essentials.Essentials.onCommand(Essentials.java:435)
[07:08:34] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[07:08:34] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[07:08:34] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1646)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1481)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10)
[07:08:34] [Server thread/WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[07:08:34] [Server thread/WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:900)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835)
[07:08:34] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733)
[07:08:34] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)

**Comment by DmitryRendov** [comment]
resolved in Orebfuscator 4.4.2
